config/routes.rb
Rails.application.routes.draw do
  root 'food_stores#index'
  devise_for :users

  resources :food_stores do
    resources :food_items, only: [:create, :edit, :destroy]
  end
end

app/models/food_item.rb
class FoodItem < ActiveRecord::Base
  belongs_to :food_store
  validates :name, presence: true
  validates :food_store_id, presence: true
end

app/models/food_store.rb
class FoodStore < ActiveRecord::Base
  belongs_to :user
  has_many :food_items
  validates :name, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def run_of_the_mill_authentication
    if current_user.nil?
      flash[:errors] = "You must sign in first!"
      redirect_to new_user_session_path
    end
  end
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :run_of_the_mill_authentication

  def create
    @food_item = FoodItem.new(food_item_params)
    @food_item.food_store_id = params[:food_store_id]
    if @food_item.save!
      flash[:notice] = "Success!"
      redirect_to :back
    else
      flash[:errors] = @food_store.errors.full_messages.join
    end
  end

  def edit
    @food_item = FoodStoreItem.find(params[:id])
    if @food_item.update(user_params)
      flash[:notice] = "Succesfully updated"
      redirect_to food_store_path(@food_item.food_store)
    else
      flash[:errors] = "Something went wrong"
      redirect_to :back
    end
  end

  def destroy
    @food_item = FoodItem.find(params[:id])
    if @food_item.food_store.user_id == current_user.id
      if @food_item.destroy!
        flash[:notice] = "Success!"
      else
        flash[:errors] = @food_item.errors.full_messages.join
      end
    else
      flash[:errors] = "Could not delete item."
    end
    redirect_to :back
  end

  private

  def food_item_params
    params.require(:food_item).permit(:name, :expiration_date, :entry_date)
  end
end

app/controllers/food_stores_controller.rb
class FoodStoresController < ApplicationController
  before_action :run_of_the_mill_authentication

  def index
    @food_stores = FoodStore.where(user_id: current_user)
  end

  def show
    @food_store = FoodStore.find(params[:id])
    @food_items = @food_store.food_items
  end

  def create
    @food_store = FoodStore.new(food_store_params)
    @food_store.user_id = current_user.id
    if @food_store.save!
      flash[:notice] = "Success!"
      redirect_to action: :index
    else
      flash[:errors] = @food_store.errors.full_messages.join
      redirect_to :back
    end
  end

  def destroy
    @food_store = FoodStore.find(params[:id])
    if @food_store.user == current_user
      if @food_store.destroy!
        flash[:notice] = "Success!"
      else
        flash[:errors] = @food_store.errors.full_messages.join
      end
    else
      flash[:errors] = "Could not delete."
    end
    redirect_to :back
  end

  private

  def food_store_params
    params.require(:food_stores).permit(:name)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def exp_calc(food_item)
    day_count = food_item.expiration_date - Date.today
    if day_count < 1
      content_tag(:span, class: "expired") do
        "EXPIRED"
      end
    elsif day_count > 10
      content_tag(:span, class: "fresh") do
        "#{day_count.to_i} days left"
      end
    end
  end
end

app/views/food_items/_food_item.html.erb
<div class="food_item">
  <span class="food_store_name">
    <%= "#{food_item.name}" %>
  </span>
  <span class="exp_message">
    <%= exp_calc(food_item) %>
  </span>
  <%= button_to "Delete", food_store_food_item_path(@food_store, food_item), method: :delete %>
</div>

app/views/food_items/_new.html.erb
<div id="itemNew" class="reveal-modal" data-reveal aria-labelledby="modalTitle"
 aria-hidden="true" role="dialog">
  <h2 id="modalTitle">Add a new food item</h2>
  <%= form_for :food_item, url: food_store_food_items_path(@food_store) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :expiration_date %>
    <%= f.text_field :expiration_date %>

    <%= f.label :entry_date %>
    <%= f.text_field :entry_date %>

    <%= f.submit "Create" %>
  <% end %>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

app/views/food_stores/_food_store.html.erb
<%= link_to "#{food_store.name}", food_store_path(food_store) %>
<%= button_to "Delete", food_store_path(food_store), method: :delete %>

app/views/food_stores/_new.html.erb
<div id="storeNew" class="reveal-modal" data-reveal aria-labelledby="modalTitle"
 aria-hidden="true" role="dialog">
  <h2 id="modalTitle">Add a new storage unit</h2>
  <%= form_for :food_stores do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit "Create" %>
  <% end %>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

app/views/food_stores/index.html.erb
<div class="container row small-medium-large-12">
  <a class="new_store button" href="#" data-reveal-id="storeNew">
    Add a storage unit
  </a>
  <div id="storeNew" class="reveal-modal" data-reveal aria-labelledby="modalTitle"
   aria-hidden="true" role="dialog">
    <h2 id="modalTitle">Add a new storage unit</h2>
    <%= form_for :food_stores do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.submit "Create" %>
    <% end %>
    <a class="close-reveal-modal" aria-label="Close">&#215;</a>
  </div>
</div>


<% if @food_stores %>
  <%= render @food_stores %>
<% else %>
  <%= "<h4>You don't have any food storage." %>
<% end %>

app/views/food_stores/show.html.erb
<h2><%= @food_store.name %></h2>
<div class="container row small-medium-large-12">
  <a class="new_item button" href="#" data-reveal-id="itemNew">
    Add a food item
  </a>
  <%= render "food_items/new" %>
</div>

<div class="food_item_container">
  <% if @food_items %>
    <%= render @food_items %><br>
  <% else %>
    <h4>This storage unit doesn't have any food!</h4>
  <% end %>
</div>

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RationIndex</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">RationIndex</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>